name: 'vessel-vision'
channels:
    - conda-forge
    - defaults
dependencies:
    - ipykernel
    - altair-all
    - dash
    - dash-bootstrap-components
    - plotly
    - tabulate  
    - lxml  
    - r-base
    - r-tidyverse
    - r-shiny
    - r-languageserver
    - r-plotly
    - pip
    - pip:
        - dash-vega-components
        - gdown
        - zipfile36  
    - pandas  
    - glob2   
    - os      



