name: vessel-vision
channels:
  - conda-forge
  - defaults
dependencies:
  - python  
  - ipykernel
  - ipython=7.31.1
  - jupyterlab  
  - backcall  
  - numpy  
  - pytz  
  - pandas  
  - altair  
  - dash
  - dash-bootstrap-components
  - plotly
  - tabulate  
  - lxml  
  - r-base
  - r-tidyverse
  - r-shiny
  - r-languageserver
  - r-plotly
  - glob2  
  - pip
  - pip:
      - dash-vega-components
      - gdown
      - zipfile36
